=== EYHN/Form/schemas/FormTemplate.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://theform.app/schemas/FormTemplate.json",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "title": { 
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "form": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "ShortAnswer/ShortAnswerTemplate.json"
          },
          {
            "$ref": "MultiSelection/MultiSelectionTemplate.json"
          },
          {
            "$ref": "SingleSelection/SingleSelectionTemplate.json"
          },
          {
            "$ref": "TextField/TextFieldTemplate.json"
          },
          {
            "$ref": "ImageView/ImageViewTemplate.json"
          }
        ]
      }
    }
  },
  "required": [
    "title",
    "form"
  ]
}

=== EYHN/Form/schemas/test/FormTemplate.json
{
  "$schema": "../FormTemplate.json",
  "title": "title",
  "description": "desc",
  "version": "0.0.0",
  "form": [
    {
      "type": "SingleSelection",
      "id": "1",
      "title": "SingleSelection 1",
      "choices": [
        {
          "type": "text",
          "text": "choice 1"
        },
        {
          "type": "text",
          "text": "choice 2"
        },
        {
          "type": "other"
        }
      ]
    }
  ]
}
